controller_joint_names: 
  - robot1_shoulder_pan_joint
  - robot1_shoulder_lift_joint
  - robot1_elbow_joint
  - robot1_wrist_1_joint
  - robot1_wrist_2_joint
  - robot1_wrist_3_joint
  - robot1_left_finger_joint
  - robot1_right_finger_joint

  - robot2_shoulder_pan_joint
  - robot2_shoulder_lift_joint
  - robot2_elbow_joint
  - robot2_wrist_1_joint
  - robot2_wrist_2_joint
  - robot2_wrist_3_joint
  - robot2_left_finger_joint
  - robot2_right_finger_joint